// องค์ประกอบ
export const elements = {
  authStatus: document.getElementById("auth-status"),
  logoutButton: document.getElementById("logout-button"),
  loginForm: document.getElementById("login-form"),
  registerForm: document.getElementById("register-form"),
  productForm: document.getElementById("product-form"),
  searchForm: document.getElementById("search-form"),
  searchInput: document.getElementById("search-input"),
  productList: document.getElementById("product-list"),
  inboxList: document.getElementById("inbox-list"),
  refreshInbox: document.getElementById("refresh-inbox"),
  showLogin: document.getElementById("show-login"),
  showRegister: document.getElementById("show-register"),
  authMessage: document.getElementById("auth-message"),
  productMessage: document.getElementById("product-message"),
  productsMessage: document.getElementById("products-message"),
  inboxMessage: document.getElementById("inbox-message"),
  productCardTemplate: document.getElementById("product-card-template"),
};
